"""Add all models

Revision ID: d65f6470a919
Revises: 
Create Date: 2025-11-23 04:27:49.922289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd65f6470a919'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('fk_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('auth_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auth_id'], ['auth_data.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('auth_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cause',
    sa.Column('cause_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('if_online', sa.Boolean(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('auth_id', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['auth_id'], ['auth_data.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('cause_id'),
    sa.UniqueConstraint('auth_id')
    )
    op.create_table('user_contact',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('user_socials',
    sa.Column('social_id', sa.Integer(), nullable=False),
    sa.Column('social', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('social_id')
    )
    op.create_table('account_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iban', sa.String(length=50), nullable=True),
    sa.Column('acc_name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['cause.cause_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iban')
    )
    op.create_table('cause_contact',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['cause.cause_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('cause_socials',
    sa.Column('social_id', sa.Integer(), nullable=False),
    sa.Column('social', sa.String(length=100), nullable=True),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['cause.cause_id'], ),
    sa.PrimaryKeyConstraint('social_id')
    )
    op.create_table('donation',
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['cause.cause_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('donation_id')
    )
    op.create_table('feedback',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['cause.cause_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('location',
    sa.Column('loc_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('contact_no', sa.String(length=50), nullable=True),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['cause.cause_id'], ),
    sa.PrimaryKeyConstraint('loc_id')
    )
    op.create_table('ngo',
    sa.Column('ngo_id', sa.Integer(), nullable=False),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.Column('year_est', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['cause.cause_id'], ),
    sa.PrimaryKeyConstraint('ngo_id'),
    sa.UniqueConstraint('cause_id')
    )
    op.create_table('volunteer',
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['cause.cause_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('volunteer_id')
    )
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('cause_id', sa.Integer(), nullable=True),
    sa.Column('ngo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['cause.cause_id'], ),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo.ngo_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('volunteer')
    op.drop_table('ngo')
    op.drop_table('location')
    op.drop_table('feedback')
    op.drop_table('donation')
    op.drop_table('cause_socials')
    op.drop_table('cause_contact')
    op.drop_table('account_details')
    op.drop_table('user_socials')
    op.drop_table('user_contact')
    op.drop_table('cause')
    op.drop_table('user')
    op.drop_table('auth_data')
    # ### end Alembic commands ###
