"""Updated foreign keys and tables

Revision ID: fed30a1bc915
Revises: d65f6470a919
Create Date: 2025-11-23 15:27:34.411614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed30a1bc915'
down_revision = 'd65f6470a919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
